apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-frontend
  namespace: guestbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      imagePullSecrets:
        - name: acr-secret       # <-- asegúrate que esté aquí, dentro del spec del template
      containers:
      - name: php-redis
        image: parcialacr20866.azurecr.io/guestbook:v8
        imagePullPolicy: Always
        ports:
        - containerPort: 80
