apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: guestbook
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: parcialacr20866.azurecr.io/redis:6.0.5
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: guestbook
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: slave
    tier: backend
